version: '3.8'
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      GID: "${GID-1000}"                                                      # Defining user file permissions
      COLLECTIONS: "crowdsecurity/linux crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules"
    # depends_on:                                                             # uncomment if running traefik in the same compose file
    #   - 'traefik'
    volumes:
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml                        # define traefik logs location in config file
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
      - traefik_logs1:/var/log/traefik/:ro                                    # docker vol for traefik logs, keep ro only for logs, (traefik_ is the name of traefik stack)
    networks:
      - crowd1                                                                # internal crowdsec + traefik network
    restart: unless-stopped

networks:
  crowd1:
    external: true

volumes:
  crowdsec-db:
  crowdsec-config:
  traefik_logs1:                                                              # docker vol for traefik logs (traefik_ is the name of traefik stack)
	  external: true
